### ISSUE TITLE
Support Pug HTML tags with hyphens

### ISSUE THREAD

**Issue by command-tab** [tommasongr/nova-vue#22] opened 2021-01-14 06:04 UTC
Thank you for this plugin, and special thanks for adding Pug support! Writing Pug is a delight compared to HTML, and I'm glad to see it getting attention in Nova.

I've noticed that while this extension supports Pug syntax, it seems to stop highlighting where tag names contain hyphens:

![image](https://user-images.githubusercontent.com/3069/104551130-20bf1000-55eb-11eb-9b7a-0049aa41f3ce.png)

Could hyphens be added so custom multi-word components get fully highlighted?

Thank you ❤️

**Comment by tommasongr** [comment] 2021-01-14 07:06
Hi there! Thank you too for enjoying nova and the extension!

I'll give it a look but that's probably due to the PUG extension, my extension just reference that other syntax.

**Comment by tommasongr** [comment] 2021-01-14 09:30
A took a look at it and I confirm the problem is not on my side.

This is a vue component using pug that shows the same problem you are pointing out.
<img width="606" alt="Schermata 2021-01-14 alle 10 25 12" src="https://user-images.githubusercontent.com/25225746/104571210-1c2e4200-5653-11eb-970e-6c78da729ccf.png">

As you can see placing the same code in a plain pug file the result is the same...
<img width="561" alt="Schermata 2021-01-14 alle 10 25 34" src="https://user-images.githubusercontent.com/25225746/104571308-3831e380-5653-11eb-9c62-ec2c69dfce0b.png">

You should reach out the folk behind Nova's Pug extension, which provides the syntax highlighting also for Nova's Vue.
https://github.com/kpmcguire/nova-pug-syntax/issues

I close the issue.

**Closed by tommasongr** 2021-01-14 09:30 UTC
